rvm:
  - 1.9.3

branches:
  only:
    - master
    - 1-3-stable
    - 2-0-stable

before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec dummier"

script: "DISPLAY=:99.0 bundle exec rake"
